version: "3"
services:
  python-dev-env:
    build:
      context: .
      dockerfile: Dockerfile.devcontainer
    volumes:
      - .:/workspaces:cached
    networks:
      - hadoop_local_cluster
    command: /bin/sh -c "while sleep 1000; do :; done"
# image: python-310-devcontainer:latest
# container_name: python-dev-env

networks:
  hadoop_local_cluster:
    external: true
