version: "3"
services:
  python-dev-env:
    image: python-310-devcontainer:latest
    container_name: python-dev-env
    volumes:
      - .:/workspaces/developer-workbench:cached
    networks:
      - hadoop_local_cluster
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  hadoop_local_cluster:
    external: true
