version: "2.2"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elastic

  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    expose:
      - 4040
      - 4041
      - 8888
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
      - 5000:5000
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - elastic
      - spark
      - bokeh

  # model_api:
  #   image: model_api
  #   container_name: model_api
  #   expose:
  #     - 5000
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - shared-workspace:/opt/workspace
  #   networks:
  #     - bokeh
  #     - spark
  #     - elastic

  front_end:
    image: front_end
    container_name: front_end
    expose:
      - 5006
    ports:
      - 5006:5006
    # volumes:
    #   - shared-workspace:/opt/workspace
    networks:
      - bokeh

  spark-master:
    image: spark-master
    container_name: spark-master
    expose:
      - 7077
      - 8080
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=6g
      - SPARK_DAEMON_JAVA_OPTS='-DXms=5g'
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=6g
      - SPARK_DAEMON_JAVA_OPTS='-DXms=5g'
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark
    depends_on:
      - spark-master

volumes:
  data01:
    driver: local

  shared-workspace:
    driver_opts:
      type: none
      device: ${SHARED_DIR}
      o: bind

networks:
  elastic:
    driver: bridge
  spark:
    driver: bridge
  bokeh:
    driver: bridge
