FROM cluster-base

ARG shared_workspace=/opt/workspace

RUN cd /usr/local/bin && \
    ln -s /usr/bin/python3 python && \
    pip install --upgrade pip

ENV SHARED_WORKSPACE=${shared_workspace}

EXPOSE 5000
WORKDIR ${SHARED_WORKSPACE}

COPY ./shared_vol/ ${SHARED_WORKSPACE}
RUN cd ${SHARED_WORKSPACE} && \
    pip install -r requirements.txt

VOLUME ${shared_workspace}

CMD ["python", "./app.py"]
